AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  This template sets up the test serverless-acm-approver

Parameters:

  DomainName:
    Type: String
  HostedZoneId:
    Type: String
  SubjectAlternativeNames:
    Type: CommaDelimitedList

Resources:
  ServerlessACMApprover:
    Type: 'AWS::Serverless::Application'
    Properties:
      Location: '../app/acm-approver.yml'
      Parameters:
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId
        SubjectAlternativeNames:
          !Join
            - ","
            - Ref: SubjectAlternativeNames
Outputs:
  CertificateArn:
    Description: "Certificate ARN"
    Value: !GetAtt ServerlessACMApprover.Outputs.CertificateArn